import Head from "next/head";
import { Box, Container } from '@chakra-ui/react'

const Main = ({children, router}) => { 
  return (
    <Box as="Main" pb={8}>
      <Head>
        <title>Yokesh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Yokesh, Portfolio, Full Stack, Developer" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.md" pt={14}>{children}</Container>
    </Box>
  )
}

export default Main