import Head from "next/head";

const Main = ({children }) => { 
  return (
    <div>
      <Head>
        <title>Yokesh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Yokesh, Portfolio, Full Stack, Developer" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{children}
    </div>
  )
}

export default Main